### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by haoranD** [chengyzhao/TextPSG#1]
Dear authors,

Many thanks for such wonderful work.

May I ask do you have any plans to release the pre-processing, training and testing codes? Is there any estimated time?

Thanks a lot.

**Comment by chengyzhao** [comment]
Hi Haoran!
Thank you for reaching out! We're currently in the process of preparing and cleaning the code to ensure it's ready for a neat release. All the code and checkpoints will be made available in one week. We appreciate your patience and support.

**Comment by haoranD** [comment]
Cheers. Looking forward to your amazing codebase.

Best

**Comment by yahooo-m** [comment]
+1
